### ISSUE TITLE
hope support mp3 

### ISSUE THREAD

**Issue by zhouxiaodian** [kailash09dabhi/OmRecorder#28] opened 2017-08-07 02:46 UTC
WAV data can be write into mp3 format with lamemp3

below project, record wav to mp3 already.
https://github.com/GavinCT/AndroidMP3Recorder

hope omrecorder can implements mp3 format support.

**Comment by kailash09dabhi** [comment] 2017-08-09 16:01
duplicate of #11

**Closed as completed by kailash09dabhi** 2017-08-09 16:01 UTC
